//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyFiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyFiles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        internal static string CopyCompliteCaption {
            get {
                return ResourceManager.GetString("CopyCompliteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копирование завершено!.
        /// </summary>
        internal static string CopyCompliteText {
            get {
                return ResourceManager.GetString("CopyCompliteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранная папка уже добавлена Выбрать другую?.
        /// </summary>
        internal static string DublicateFolder {
            get {
                return ResourceManager.GetString("DublicateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете папку, источник файлов.
        /// </summary>
        internal static string FolderBrowserDescription {
            get {
                return ResourceManager.GetString("FolderBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать еще папку?.
        /// </summary>
        internal static string MessageBoxNextFolderText {
            get {
                return ResourceManager.GetString("MessageBoxNextFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В выбранной папке нет файлов
        ///Выбрать другую папку?.
        /// </summary>
        internal static string SfTextBoxNoFilesInFolder {
            get {
                return ResourceManager.GetString("SfTextBoxNoFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!!!.
        /// </summary>
        internal static string SfTextBoxNoFilesInFolderCaption {
            get {
                return ResourceManager.GetString("SfTextBoxNoFilesInFolderCaption", resourceCulture);
            }
        }
    }
}
